### PR TITLE
NETOBSERV-1283: Enable netns mount for privileged pods

### PR DESCRIPTION
**Pull request by msherif1234**
## Description

for privileged pods we need to mount /var/run/netns to be able to view VF interface in pod netns
## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [ ] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [ ] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [X] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by bn222** [comment]
Debugged and tested it together with @msherif1234 . lgtm.

**Review by jotak — DISMISSED** [review]
lgtm, thanks!

**Comment by jotak** [comment]
thanks @msherif1234 @memodi !
/lgtm
/approve

**Comment by jotak** [comment]
/approve
(sorry idk what i'm doing🥴 )

**Pull request merged**
