### PR TITLE
Push temporary bundle/catalog

### PR DESCRIPTION
**Pull request by jotak**

### CODE REVIEW

**Comment by jotak** [comment]
Hey @memodi 
The discussion on https://issues.redhat.com/browse/NETOBSERV-872 made me think we can also do something pretty simple like this. We can also generate temporary bundles & catalogs per PR with "ok-to-test"
Here's an example of the comment that is generated: https://github.com/netobserv/network-observability-operator/pull/292#issuecomment-1464020230

**Comment by nathan-weinberg** [comment]
@memodi perhaps we should update our [testing steps](https://docs.google.com/document/d/12fbO28KimeAxn25bTCC6tc_MqJcLwODVQ_pf0a1dgo8/edit#) to simplify the premerge testing process with this new functionality

**Comment by memodi** [comment]
> @memodi perhaps we should update our [testing steps](https://docs.google.com/document/d/12fbO28KimeAxn25bTCC6tc_MqJcLwODVQ_pf0a1dgo8/edit#) to simplify the premerge testing process with this new functionality

Yes, we should after trying and testing out this method :)

**Comment by jotak** [comment]
/approve

@memodi @nathan-weinberg @Amoghrd you can start testing as soon as it's merged

**Pull request merged**
