### PR TITLE
Move FLP log level in the example CR to error

### PR DESCRIPTION
**Pull request by eranra**
No reason for the example CR's to be in info level for FLP. If needed this can be changed dynamically. To be able to use NOO similar to customers best is to use error level.

### CODE REVIEW

**Comment by jotak** [comment]
Is it to avoid the messages like `Can't find kubernetes info for IP  ...` ?
I agree this is annoying ... but on the other hand I find the starting logs quite useful in general and good to have by default. So, I don't know what to think ...

**Comment by eranra** [comment]
@jotak yes ... this message is filling up the log .... so moving this specific message to debug is also a totally reasonable solution.  BUT we will need a new release for this to effect, right?

**Comment by eranra** [comment]
@jotak I need your view on what to do with this PR? we merged the FLP change  https://github.com/netobserv/flowlogs-pipeline/commit/8d711a2d4f139b1ae89f1c6589dd1789c6ce5d5a so need to decide if we drop or merge this one?

**Comment by jotak** [comment]
I'd say now the FLP change is merged we can keep the Info logging by default, no?

**Comment by eranra** [comment]
OK ... so closing this PR without merging. I hope this will not cause any more troubles ....

**Pull request closed without merging**
