### PR TITLE
NETOBSERV-1371: Disable http/2 in kube-rbac-proxy [1.4 backport]

### PR DESCRIPTION
**Pull request by jotak**
## Description

Disable http/2 in kube-rbac-proxy

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [x] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [ ] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by msherif1234** [comment]
where is the logic in main that disable http2 for wh ?

**Review by OlivierCazade — APPROVED** [review]

**Comment by Amoghrd** [comment]
@jotak I ran the automated backend regression on this operator image and I see failures related to metrics consistently
`fail [/home/jenkins/ws/workspace/ocp-common/ginkgo-test/private/test/extended/netobserv/metrics.go:60]: 0 results`
`returned for query sum(netobserv_ingest_flows_processed)`
`10-23 15:42:19.428  Expected`
`10-23 15:42:19.428      <int>: 0`
`10-23 15:42:19.428  to be >=`
`10-23 15:42:19.428      <int>: 1`
Here the jenkins job for reference [211024](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/ginkgo-test/211024/console)
I reran but faced the same issue.

**Comment by jotak** [comment]
> where is the logic in main that disable http2 for wh ?

this was already done in 1.4.1 : https://github.com/netobserv/network-observability-operator/commit/972033fba009a57f068acaa4afe3cf31b254d184#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261

The only missing bit is with kube-rbac-proxy

**Comment by jotak** [comment]
@Amoghrd I think it must be something else, not related to this PR, because kube-rback-proxy is only proxying the operator metrics; and the one you mention comes from FLP, which serves directly without proxy.
I just deployed the bundle on my cluster and checked for `sum(netobserv_ingest_flows_processed)`, I get some results...
Can we take  a look at your cluster directly ? (I don't see anything from the jenkins logs)

**Comment by Amoghrd** [comment]
As @jotak mentioned since the tests are using the upstream operator, the user-workload-monitoring is not set leading to no metrics. After enabling it, could observe the metrics. Will test the metrics post-merge. PR looks good to merge.
/label qe-approved

**Comment by jotak** [comment]
thx @Amoghrd 
/approve

**Pull request merged**
