### PR TITLE
NETOBSERV-1605: add flow filter to ebpf agent dashboard

### PR DESCRIPTION
**Pull request by msherif1234**
## Description

add flow filter to ebpf agent health dashboard
## Dependencies

https://github.com/netobserv/netobserv-ebpf-agent/pull/316

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [ ] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [ ] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by msherif1234** [comment]
using this fc config 
```sh
flowFilter:
        action: Accept
        cidr: 0.0.0.0/0
        destPorts: 0
        enable: true
        ports: 53
        protocol: UDP
      metrics:
        enable: true
```

image

**Comment by jotak** [comment]
@msherif1234 the dashboard code itself looks good but there must be something wrong with this metrics as the **rate** keeps increasing (the counter always increases but the rate should not)

**Comment by msherif1234** [comment]
> ```shell
> IMAGE=quay.io/netobserv/network-observability-operator:72a0090 make deploy
> ```

Added missing logic to reset counters after reading them https://github.com/netobserv/netobserv-ebpf-agent/pull/316
image

**Pull request merged**
