### PR TITLE
Remove mention 'cannot be updated' on requests/limits

### PR DESCRIPTION
**Pull request by jotak**

### CODE REVIEW

**Comment by jotak** [comment]
I'll backport it to 4.12 as it has an impact on the generated doc, which is wrong in that regard

**Review by mariomac — APPROVED** [review]
Shall we backport to `release-4.12`?

**Review by OlivierCazade — APPROVED** [review]

**Comment by memodi** [comment]
> I'll backport it to 4.12 as it has an impact on the generated doc, which is wrong in that regard

to understand impact on downstream docs, are those copied/pasted from here upstream?

**Review by memodi — APPROVED** [review]

**Pull request merged**
