### PR TITLE
NETOBSERV-712 Add metric to measure number of flows per namespace

### PR DESCRIPTION
**Pull request by jotak**
E.g. to get netobserv flows in percentage of total:

```
100 * (sum (rate(netobserv_namespace_flows_total{SrcK8S_Namespace="netobserv"}[1m])) + sum (rate(netobserv_namespace_flows_total{SrcK8S_Namespace!="netobserv", DstK8S_Namespace="netobserv"}[1m]))) / sum (rate(netobserv_namespace_flows_total[1m]))
```

image

### CODE REVIEW

**Comment by memodi** [comment]
thanks @jotak  - would this be correct query for non-internal netobserv traffic:
```
(sum (rate(netobserv_namespace_flows_total{SrcK8S_Namespace!="netobserv"}[1m])) + sum (rate(netobserv_namespace_flows_total{DstK8S_Namespace!="netobserv"}[1m])))
```

**Comment by jotak** [comment]
@memodi if I'm correct it's simpler than that, it's just:
```
sum (rate(netobserv_namespace_flows_total{SrcK8S_Namespace!="netobserv",DstK8S_Namespace!="netobserv"}[1m])
```

= all flows where neither source nor dest are from netobserv namespace

**Review by OlivierCazade — APPROVED** [review]
LGTM

**Comment by jotak** [comment]
thanks @memodi @OlivierCazade 
/approve

**Pull request merged**
