### PR TITLE
Add make script to update images

### PR DESCRIPTION
**Pull request by jotak**

### CODE REVIEW

**Review by OlivierCazade — APPROVED** [review]
Thanks!

**Comment by jotak** [comment]
/hold

@mariomac we can merge your PR first, then I'll update the doc (and add the -c manager) in mine

**Comment by mariomac** [comment]
@jotak ok. It's merged just now

**Comment by jotak** [comment]
/unhold
ready

**Review by mariomac — APPROVED** [review]
👏🏻

**Pull request merged**
