### PR TITLE
Change HOST/PORT env to TARGET_HOST / TARGET_PORT

### PR DESCRIPTION
**Pull request by jotak**
Depends on https://github.com/netobserv/netobserv-ebpf-agent/pull/303

(was discussed here https://github.com/netobserv/netobserv-ebpf-agent/pull/291#discussion_r1520076865)

### CODE REVIEW

**Review by jpinsonneau — APPROVED** [review]
Tested and works fine; I don't know why e2e was failing :thinking:

**Comment by jotak** [comment]
/approve
thanks @jpinsonneau @msherif1234

**Pull request merged**
