### PR TITLE
NETOBSERV-704 Netflow traffic page doesn't appear sometimes

### PR DESCRIPTION
**Pull request by jpinsonneau**
Added mention on how to check and restart console pods to clear plugin cache

### CODE REVIEW

**Review by mariomac — APPROVED** [review]

**Comment by Amoghrd** [comment]
Small nit here @jpinsonneau all other commands in the doc use kubectl, for uniformity according to me its better to use kubectl instead of oc.

**Comment by jpinsonneau** [comment]
> Small nit here @jpinsonneau all other commands in the doc use kubectl, for uniformity according to me its better to use kubectl instead of oc.

Usually we use `kubectl` for upstream and `oc` for downstream. Since this workaround is only openshift related, I have chosen `oc` here. Does it makes sense ?

**Comment by Amoghrd** [comment]
ah okay, got it @jpinsonneau 👍

**Pull request merged**
