### PR TITLE
NETOBSERV-660: Create metric section

### PR DESCRIPTION
**Pull request by OlivierCazade**
As an anticipation to more work regarding metrics in FLP and before going GA, create sub metric section in processor section.

### CODE REVIEW

**Review by mariomac — APPROVED** [review]

**Comment by jotak** [comment]
/hold
let see with @memodi if we want it in 0.1.5

**Comment by memodi** [comment]
> /hold let see with @memodi if we want it in 0.1.5

thanks @jotak, seems straightforward change, should be fine adding it in if its already reviewed and good to be approved.

**Review by jotak — APPROVED** [review]

**Comment by memodi** [comment]
/qe-approved
tested pre-merge.

**Pull request merged**
