### PR TITLE
NETOBSERV-1747: trigger stored resource migration on operator startup

### PR DESCRIPTION
**Pull request by jotak**
## Description

Borrowing and adapting code from Tekton https://github.com/tektoncd/operator/blob/v0.72.0/pkg/reconciler/shared/tektonconfig/upgrade/helper/migrator.go

On startup, the operator will start the migration process, which is basically a noop if resources are already in the correct stored version, or else which triggers a conversion + rewrite by the api server (which itself relies on our conversion webhooks). The CRD status is then updated to only mention the current stored version.

## Testing

Testing is not straightforward, here's the steps I did:

```bash
# Install an older CRD version where storedVersion was different (you don't need to install the operator, just the CRD is sufficient)
git checkout release-1.5
make install
oc apply -f config/samples/flows_v1beta1_flowcollector.yaml

# Check stored version is v1beta1
oc get crd flowcollectors.flows.netobserv.io -ojsonpath='{.status.storedVersions}'
["v1beta1"]

# Update the CRD to the new version
git checkout main # Assuming your main branch is up-to-date, else please update it
bin/kustomize build config/crd | kubectl apply --server-side --force-conflicts -f -

# Check stored version have both v1beta1 and v1beta2
oc get crd flowcollectors.flows.netobserv.io -ojsonpath='{.status.storedVersions}'
["v1beta1","v1beta2"]

# <-- AT THIS POINT, if nothing is done and later the v1beta1 version is removed, this would break the upgrades

# Deploy the operator (this PR)
git checkout (this PR)
make deploy VERSION=... USER=...

oc get crd flowcollectors.flows.netobserv.io -ojsonpath='{.status.storedVersions}'
["v1beta2"]
```

You may also take a look at the operator logs. It will probably show some temporary errors, due to the webhook server not being ready yet when trying migration - the operator is just going to retry with an exponential backoff:

```
2024-09-17T11:59:40.460Z	INFO	ensuring stored resources are up to date
2024-09-17T11:59:40.460Z	INFO	migrating group version	{"crdGroup": "flowcollectors.flows.netobserv.io"}
W0917 11:59:40.535415       1 reflector.go:561] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go:106: failed to list *v1beta2.FlowCollector: conversion webhook for flows.netobserv.io/v1beta1, Kind=FlowCollector failed: Post "https://netobserv-webhook-service.netobserv.svc:443/convert?timeout=30s": no endpoints available for service "netobserv-webhook-service"
...
2024-09-17T11:59:51.723Z	INFO	migration completed	{"crdGroup": "flowcollectors.flows.netobserv.io"}
2024-09-17T11:59:51.723Z	INFO	migrating group version	{"crdGroup": "flowmetrics.flows.netobserv.io"}
2024-09-17T11:59:51.807Z	INFO	migration completed	{"crdGroup": "flowmetrics.flows.netobserv.io"}
```

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [x] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [x] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [x] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Review by jpinsonneau — APPROVED** [review]
LGTM, maybe just need some testing around the retry params (steps / duration ...) ?

**Review by OlivierCazade — APPROVED** [review]
LGTM

**Comment by jotak** [comment]
> LGTM, maybe just need some testing around the retry params (steps / duration ...) ?

done: [e352caa](https://github.com/netobserv/network-observability-operator/pull/780/commits/e352caa016dada5afdee50babd5e822f7e7d2fe6)

**Comment by Amoghrd** [comment]
@jotak I tried the above steps but could not see the migration happening. I still see v1beta1 in the storedVersion list. I did capture the controller logs and have attached it below. 

[netobserv-controller-manager-7fd689f688-psz8z-manager.log](https://github.com/user-attachments/files/17722781/netobserv-controller-manager-7fd689f688-psz8z-manager.log)

**Comment by jotak** [comment]
> @jotak I tried the above steps but could not see the migration happening. I still see v1beta1 in the storedVersion list. I did capture the controller logs and have attached it below.
> 
> [netobserv-controller-manager-7fd689f688-psz8z-manager.log](https://github.com/user-attachments/files/17722781/netobserv-controller-manager-7fd689f688-psz8z-manager.log)

@Amoghrd OK there was 2 issues:
- first this PR had to be rebased so deploying the operator based on main's CRD was generating errors
- second, something was missing in my test steps, because this PR includes RBAC changes it needs to be deployed from the PR itself; so I added `git checkout (this PR)` in the test steps.

**Comment by Amoghrd** [comment]
That helped thanks Joel!
/label qe-approved

**Pull request merged**
