### PR TITLE
Fix goflow-kube deployment - works with configmap

### PR DESCRIPTION
**Pull request by jotak**
Implement installing a configmap for goflow-kube

### CODE REVIEW

**Comment by jotak** [comment]
@memodi this should fix the issue that we have when using goflow-kube latest image

**Comment by memodi** [comment]
@jotak I build an IMG off this branch and deployed in a cluster, however when I deploy the operator and then try to apply the flows config, I still get an error as below:

`$ oc apply -f config/samples/flows_v1alpha1_flowcollector.yaml
flowcollector.flows.netobserv.io/flowcollector-sample created
memodi@memodi-mac:/Users/memodi/workspaces/repos/netobserv/jotak/network-observability-operator  (gfk-configmap=)
$ oc get all                                                  
NAME                                                READY   STATUS    RESTARTS   AGE
pod/goflow-kube-6557855ff4-4t4bt                    0/1     Error     0          8s
pod/netobserv-controller-manager-56c7d557dd-26twz   2/2     Running   0          52s

NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/goflow-kube                 ClusterIP   172.30.203.158   <none>        2055/UDP   8s
service/netobserv-metrics-service   ClusterIP   172.30.234.141   <none>        8443/TCP   52s

NAME                                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/goflow-kube                    0/1     1            0           8s
deployment.apps/netobserv-controller-manager   1/1     1            1           52s

NAME                                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/goflow-kube-6557855ff4                    1         1         0       8s
replicaset.apps/netobserv-controller-manager-56c7d557dd   1         1         1       52s
memodi@memodi-mac:/Users/memodi/workspaces/repos/netobserv/jotak/network-observability-operator  (gfk-configmap=)
$ oc logs -p pod/goflow-kube-6557855ff4-4t4bt
/bin/sh: /kube-enricher: No such file or directory
`

**Comment by jotak** [comment]
@memodi it's weird, the error suggests you don't have the deployed the new code (it shouldn't try to run `/bin/sh: /kube-enricher` now, but `/bin/sh: /goflow-kube` instead.
One possible explanation is if you create builds with reusing the same image name .. as the operator's pull policy is "IfNotPresent", it won't use your latest build when the image is already in the container registry.

If so, to fix that you can either use always a different image name (that's what I do, I run `make image-build image-push deploy IMG="quay.io/jotak/network-observability-operator:v0.0.1-26"`, every time incrementing the version to keep using different images)

Or you can modify the operator spec : `oc edit deployment netobserv-controller-manager -n network-observability`, locate where `network-observability-operator` is defined and change pull policy to `Always`. (but it might get overwritten the next time your deploy it, so the first option (always using a different image name) is better IMO)

**Review by mariomac — APPROVED** [review]

**Review by jpinsonneau — APPROVED** [review]

**Comment by jpinsonneau** [comment]
> Or you can modify the operator spec : `oc edit deployment netobserv-controller-manager -n network-observability`, locate where `network-observability-operator` is defined and change pull policy to `Always`. (but it might get overwritten the next time your deploy it, so the first option (always using a different image name) is better IMO)

I personally added `imagePullPolicy: Always` to network-observability-operator/config/manager/manager.yaml file so it keeps pulling each time I rebuild

**Review by OlivierCazade — APPROVED** [review]

**Comment by memodi** [comment]
@jotak yes, I think there's something wrong how the image is pushed to my repo and pulled,  so I think I'll just try again once the code is merged to main. I'll approve for now based on code-inspection.

/label qe-approved

**Comment by jotak** [comment]
> @memodi: The label(s) `qe-approved` cannot be applied, because the repository doesn't have them.

(ok I'm creating this label for next time :)

**Comment by jotak** [comment]
thanks for the reviews

**Pull request merged**
