### PR TITLE
NETOBSERV-1935: enable metrics from list/nested fields

### PR DESCRIPTION
**Pull request by jotak**
## Description

Allow to generate metrics from list fields (and later nested fields), such as Interfaces or NetworkEvents.

This PR includes an example: 

```yaml
apiVersion: flows.netobserv.io/v1alpha1
kind: FlowMetric
metadata:
  name: per-interface
  namespace: netobserv
spec:
  metricName: per_interface
  type: Counter
  labels: [Interfaces]
  flatten: [Interfaces]
  remap:
    Interfaces: interface
```

When deployed, using a promQL query such as:

```
topk(10, sum(rate(netobserv_per_interface[1m])) by (interface) )
```
will show flows per individual interfaces instead of an arbitrary list of interfaces.

**This is also adding new predefined metrics** and charts when the NetworkEvents feature is enabled:

Capture d’écran du 2024-11-19 11-54-11

## Dependencies

FLP: https://github.com/netobserv/flowlogs-pipeline/pull/739

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [x] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labeled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [x] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by jotak** [comment]
/hold
go mod to be updated after https://github.com/netobserv/flowlogs-pipeline/pull/739 is merged

**Comment by jotak** [comment]
/unhold
flp pr was merged

**Review by jpinsonneau — APPROVED** [review]

**Comment by memodi** [comment]
@jotak I am approving this but I have some questions, I'll post on JIRA

/label qe-approved

**Comment by jotak** [comment]
thanks @memodi !
/approve

**Pull request merged**
