### PR TITLE
NETOBSERV-1513: Remove v1alpha1, deprecate v1beta1, store v1beta2

### PR DESCRIPTION
**Pull request by jotak**
## Description

Spring cleaning:
- Remove v1alpha1
- deprecate v1beta1
- store v1beta2

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [ ] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [ ] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [x] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Review by jpinsonneau — APPROVED** [review]
Looks good to me, thanks !

**Comment by msherif1234** [comment]
do u need to also remove `hack-crd-for-test` from `generate` makefile rule and calls to `hack/crd2csvSpecDesc.sh` ?

**Comment by jotak** [comment]
> do u need to also remove `hack-crd-for-test` from `generate` makefile rule and calls to `hack/crd2csvSpecDesc.sh` ?

we can remove it ... or keep it because we will probably need it again when we'll introduce a new API ?

**Comment by jotak** [comment]
@msherif1234 hack disabled: https://github.com/netobserv/network-observability-operator/pull/577/commits/c11d720b7ec3681d287b06bc506fcdc26ee32979

Note that `hack/crd2csvSpecDesc.sh` is a different thing and unrelated, we need to keep it (it helps to generate automatically specDescriptors for the CSV, which is used in the console OLM form, to make sure we don't forget anything there)

**Pull request merged**
