### PR TITLE
NETOBSERV-1737 consolePlugin fails to get deployed on 4.17 cluster

### PR DESCRIPTION
**Pull request by jpinsonneau**
## Description

Update console plugin API to work on OCP 4.17+
## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [X] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [X] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by msherif1234** [comment]
how about calling the pkt consoleapilatest and u can change v1alpha1 to v1 and if it changed again to v2 or something u will change in one place ?

**Comment by jotak** [comment]
thanks @jpinsonneau !
/lgtm

For 4.12 cluster or before (which are unsupported), people will have to explicitly turn off the plugin deployment. They can still use the test console btw, if I'm correct.

**Comment by memodi** [comment]
> For 4.12 cluster or before (which are unsupported), people will have to explicitly turn off the plugin deployment. They can still use the test console btw, if I'm correct.

even though 4.12 support has ended, it has extended support running through Jan 17 2025. I am not sure what's the recourse if someone running on 4.12 until then and upgrades to 1.7?

**Comment by jotak** [comment]
@memodi in midstream I removed 4.12 support for 1.7, meaning that the operator should not be available for upgrade on these clusters. That was also needed for FIPS. I think (hope) this plan can work - and in case of critical bugs we can still release a 1.6.2

**Comment by memodi** [comment]
> @memodi in midstream I removed 4.12 support for 1.7, meaning that the operator should not be available for upgrade on these clusters. That was also needed for FIPS. I think (hope) this plan can work - and in case of critical bugs we can still release a 1.6.2 for people running on 4.12

SGTM.

/label qe-approved

**Comment by jpinsonneau** [comment]
Thanks everyone ! Merging now

**Pull request merged**
