### PR TITLE
adding workflow to build catalog bundle on push to main

### PR DESCRIPTION
**Pull request by memodi**
This should help by creating subscription of NOO catalog image developed from `main` branch as an alternative to `make deploy` target

### CODE REVIEW

**Review by jpinsonneau — APPROVED** [review]
LGTM (not tested)

**Comment by memodi** [comment]
cc @jotak

**Comment by memodi** [comment]
I am closing this PR, didn't realize this is created off my `main` branch. I'll create another PR from the working branch.

**Pull request closed without merging**
