### PR TITLE
NETOBSERV-1568: reintroduce finalizer check to remove any remaining finalizer

### PR DESCRIPTION
**Pull request by jotak**
## Description

Since removing ipfix, we don't use finalizers anymore. However users upgrading from a 1.5 will still have one set in their CR. So we need, for a release, to continue checking for the finalizer, and remove it if found.

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [x] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [x] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by memodi** [comment]
@jotak - I tried to upgrade test with pre-merge catalog, but unable with downstream 1.5 and upstream pre-merge, QE testing would have to occur on downstream bundle for this change.

**Comment by jotak** [comment]
> @jotak - I tried to upgrade test with pre-merge catalog, but unable with downstream 1.5 and upstream pre-merge, QE testing would have to occur on downstream bundle for this change.

What I did to test was installing downstream 1.5, then downstream 1.6 (the one that is buggy) and then I manually changed the operator image from the installed CSV to the upstream one.
Otherwise, to switch from a downstream catalog to an upstream one, IIRC there's a couple of more things to do like replacing the "replaces" key in CSV

**Comment by memodi** [comment]
> What I did to test was installing downstream 1.5, then downstream 1.6 (the one that is buggy) and then I manually changed the operator image from the installed CSV to the upstream one. And then I was able to delete the FlowCollector.

thanks @jotak . I was able to verify with this approach.

/label qe-approved

**Pull request merged**
