### PR TITLE
Update Grafana dashboard

### PR DESCRIPTION
**Pull request by jotak**
Add flows by namespaces + total flows metrics

Capture d’écran de 2022-01-26 15-53-41

### CODE REVIEW

**Comment by jotak** [comment]
cc @memodi I don't know if you use grafana, if so this might interest you

**Comment by memodi** [comment]
> cc @memodi I don't know if you use grafana, if so this might interest you

@jotak Thanks,  I do use Grafana, having dashboard JSON will be very helpful. Just confirm, the flows/per second metric isn't reported yet, correct?

**Comment by jotak** [comment]
> Just confirm, the flows/per second metric isn't reported yet, correct?

Actually yes it's already there, provided from Loki. It's not there as a prometheus metric though. But we can get it from Loki / LogQL to get the number of log entries (so, flows) per second

**Comment by memodi** [comment]
> > Just confirm, the flows/per second metric isn't reported yet, correct?
> 
> Actually yes it's already there, provided from Loki. It's not there as a prometheus metric though. But we can get it from Loki / LogQL to get the number of log entries (so, flows) per second

that's awesome. Thanks for adding that in!

**Review by mariomac — APPROVED** [review]

**Review by jpinsonneau — APPROVED** [review]

**Pull request merged**
