### PR TITLE
Allow modifying namespace from web console

### PR DESCRIPTION
**Pull request by msherif1234**
image

### CODE REVIEW

**Comment by msherif1234** [comment]
@jotak I think there is still a value allowing custom NS instead of just having the default `openshift-operators` NS

**Comment by jotak** [comment]
iirc `openshift-*` namespaces are reserved for in-payload operators

**Comment by msherif1234** [comment]
> iirc, new `openshift-*` namespaces are reserved for in-payload operators, but I'm not totally sure The OLM team might know, but perhaps you already asked them ?

I didn't see any such limitation here https://docs.openshift.com/container-platform/4.8/operators/operator_sdk/osdk-generating-csvs.html#osdk-suggested-namespace_osdk-generating-csvs

**Review by jotak — CHANGES_REQUESTED** [review]
cf previous comment, I have a doubt that this change is actually desirable

**Pull request closed without merging**
