### PR TITLE
NETOBSERV-1326: Add metrics for packets drop

### PR DESCRIPTION
**Pull request by msherif1234**
## Description

add metrics for packets drop feature, using same strategy as in #408 

testing with `cluster-bot` using OCP cluster

1- enable metrics
```sh
oc get cm -n openshift-monitoring  cluster-monitoring-config -o yaml
apiVersion: v1
data:
  config.yaml: |-
    enableUserWorkload: true <<<<
    prometheusK8s:

      volumeClaimTemplate:
        metadata:
          name: prometheus-data
          annotations:
            openshift.io/cluster-monitoring-drop-pvc: "yes"
        spec:
          resources:
            requests:
              storage: 20Gi
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-02T10:31:37Z"
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  resourceVersion: "72651"
  uid: 5bc8c0a3-1b13-4dbd-9746-e485e5ee15da
```
2- enable pktdrop feature and enable all tags
```sh
 agent:
       type: EBPF
       ebpf:
         privileged: true  <<<
         features:  
           - "PacketDrop"   <<<
     processor:
         ignoreTags: []

```
## Dependencies
https://github.com/netobserv/flowlogs-pipeline/pull/478

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [X] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [X] Does this PR require product documentation?
  * [X] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [X] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [X] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Review by jpinsonneau — CHANGES_REQUESTED** [review]
It's a bit weird in terms of naming to have `packets-drop-packets` / `packets-drop-bytes`.
We may use `dropped-packets` / `dropped-bytes` instead ?

Otherwise code looks good !

**Comment by msherif1234** [comment]
image

image

image

**Review by jpinsonneau — APPROVED** [review]
LGTM, thanks @msherif1234

**Comment by jpinsonneau** [comment]
Holding this as it will need to be reworked with [NETOBSERV-1284](https://issues.redhat.com/browse/NETOBSERV-1284) approach

**Pull request closed without merging**
