### PR TITLE
Use new FLP API to build pipeline

### PR DESCRIPTION
**Pull request by jotak**
draft, requires not-merged https://github.com/netobserv/flowlogs-pipeline/pull/213

### CODE REVIEW

**Review by mariomac — APPROVED** [review]
Much cleaner now. Thanks!

**Comment by jotak** [comment]
Ready for review, now pointing to the actual FLP version.
This PR is necessary to fix kafka pipeline (due to a breaking change in https://github.com/netobserv/flowlogs-pipeline/pull/213 )

**Review by OlivierCazade — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
