### PR TITLE
NETOBSERV-116 : Fix deployment in a different namespace

### PR DESCRIPTION
**Pull request by OlivierCazade**
Enabled proxy alias to have a backend route that do not depend on the namespace :
- needed to upgrade openshift/api and its dependencies
- needed to switch to golang 1.17 because of the dependencies upgrades

This PR needs to be merged with the plugin PR.

### CODE REVIEW

**Comment by OlivierCazade** [comment]
/hold
To coordinate PR merge

**Review by mariomac — APPROVED** [review]

**Review by jpinsonneau — APPROVED** [review]

**Pull request merged**
