### PR TITLE
NETOBSERV-1005 dashboard: use sum...by

### PR DESCRIPTION
**Pull request by jotak**
- Fix metrics aggregations by using sum...by
- Do not split by FLP pod reporter as it's an implementation detail

1.3 backport: https://github.com/netobserv/network-observability-operator/pull/358

### CODE REVIEW

**Review by OlivierCazade — APPROVED** [review]
LGTM

**Review by jpinsonneau — APPROVED** [review]

**Comment by memodi** [comment]
@jotak this overall looks good to me. It would have been nice to have it limited to Top 5 with `topK` query but based on some reading it looks like when plotting w/ graphs that's not possible. Grafana has some features but probably OCP console Dashboards doesn't have it. 

Also, could we do something about those empty parentheses? quick search online I didn't find any straightforward solution to handle this in prometheus query. For our netflow-traffic page, we do that by replacing it with `non-pods` I guess that's done in console-plugin.

image

So if no changes are being further treat this as `/label qe-approved` and feel to free to merge it.

**Comment by jotak** [comment]
@memodi there's probably something we can do with [label_replace](https://prometheus.io/docs/prometheus/latest/querying/functions/#label_replace) , I'll make a try

**Comment by jotak** [comment]
@memodi so my last commit should address your second comment. On the first one (the top5 thing), yeah I didn't find a way to force restricting 5 outputs, and anyway I thought having a bit more than 5 could be interesting, hence I just removed the "Top 5" mention from the title

**Comment by jotak** [comment]
let me try one last thing: I'd like to remove the node-to-node or external-to-node traffic from the workloads-kind of metrics

**Comment by jotak** [comment]
Ok, I've modified the "workloads" graph to exclude node-to-node traffic, so it's node overlapping with the other graph dedicated to nodes

Capture d’écran du 2023-06-02 12-06-07

wdyt?

**Comment by memodi** [comment]
> wdyt?

I am yet to try, but this looks great :D , thank you!

**Comment by jotak** [comment]
thanks!
/approve
There's the backporting PR then to /lgtm: https://github.com/netobserv/network-observability-operator/pull/358

**Pull request merged**
