### PR TITLE
NETOBSERV-764: conversion fallback on ingester url

### PR DESCRIPTION
**Pull request by jpinsonneau**
## Description

This PR fix the empty loki querier url issue in conversion webhook

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [X] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [X] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by Amoghrd** [comment]
Think this is a simple fix, can be merged without QE testing. wdyt @nathan-weinberg?

**Comment by nathan-weinberg** [comment]
@Amoghrd agreed, but if it's alright with @jpinsonneau I want to check out some other modes as well before merging this in case we need any other changes!

**Comment by nathan-weinberg** [comment]
I deployed the premerge image of the operator using the same [v1beta1 CRD](https://raw.githubusercontent.com/openshift-qe/ocp-qe-perfscale-ci/netobserv-perf-tests/scripts/netobserv/flows_v1beta1_flowcollector.yaml) as Amogh and pods came up and seem to be processing flows/generating graphs, this is how the conversion func handled the conversion to `v1beta2` for the relevant loki section
```yaml
  loki:
    timeout: 10s
    microservices:
      ingesterUrl: 'http://loki-distributor:3100/'
      querierUrl: 'http://loki-query-frontend:3100/'
      tenantID: netobserv
      tls:
        caCert: {}
        userCert: {}
    maxRetries: 2
    enable: true
    mode: Manual
    maxBackoff: 5s
    manual:
      authToken: FORWARD
      ingesterUrl: >-
        https://lokistack-gateway-http.netobserv.svc.cluster.local:8080/api/logs/v1/network/
      querierUrl: >-
        https://lokistack-gateway-http.netobserv.svc.cluster.local:8080/api/logs/v1/network/
      statusTls:
        caCert: {}
        userCert: {}
      tenantID: network
      tls:
        caCert:
          certFile: service-ca.crt
          name: lokistack-gateway-ca-bundle
          type: configmap
        enable: true
        userCert: {}
    lokiStack:
      name: loki
    staticLabels:
      app: netobserv-flowcollector
    monolithic:
      tenantID: netobserv
      tls:
        caCert: {}
        userCert: {}
      url: 'http://loki:3100/'
    batchWait: 1s
    minBackoff: 1s
    batchSize: 10485760
```

**Comment by jpinsonneau** [comment]
Thanks @nathan-weinberg & @Amoghrd 
Let's merge !

**Pull request merged**
