### PR TITLE
NETOBSERV-856 [1.2 backport] Fix infinite reconcile & add more debugging utility

### PR DESCRIPTION
**Pull request by jotak**
Backport of https://github.com/netobserv/network-observability-operator/pull/262

### CODE REVIEW

**Comment by memodi** [comment]
/qe-approved 
tested pre-merge

**Review by memodi — APPROVED** [review]

**Comment by memodi** [comment]
@jotak - is something wrong with labels? I don't see qe-approved label being added.

**Comment by jotak** [comment]
@memodi trying this way:
/label qe-approved

**Comment by jotak** [comment]
@memodi if I'm correct this is either `/qe-approve` (without "d") or `/label qe-approved` (with "d")

**Pull request merged**
