### PR TITLE
NETOBSERV-1107: Add GoMemLimit env setting to prevent ebpf agent OOM conditions

### PR DESCRIPTION
**Pull request by msherif1234**
https://weaviate.io/blog/gomemlimit-a-game-changer-for-high-memory-applications

### CODE REVIEW

**Review by jpinsonneau — APPROVED** [review]
LGTM in terms of code, thanks @msherif1234 !

**Comment by jotak** [comment]
btw we may do that on FLP as well

**Comment by msherif1234** [comment]
> btw we may do that on FLP as well

FLP has memory issues too ?

**Review by jpinsonneau — DISMISSED** [review]
/lgtm

**Comment by jotak** [comment]
/lgtm
thanks!

**Pull request merged**
