### PR TITLE
NETOBSERV-1003: Added monitoring role to bundle

### PR DESCRIPTION
**Pull request by OlivierCazade**
Add monitoring role to the bundle.

### CODE REVIEW

**Comment by OlivierCazade** [comment]
/hold

Testing

**Review by memodi — DISMISSED** [review]
LGTM
I tried testing  using `make-deploy` but it did not deploy operator in `openshift-netobserv-operator` NS and also had to update `DOWNSTREAM_DEPLOYMENT` variable. If your testing so far  looks good. I think we should go ahead merge it and can do further testing on Downstream builds.

/label qe-approved

**Comment by msherif1234** [comment]
@OlivierCazade do u think it’s better to group role and role_binding for Prometheus with the rest under Config/rbac folder ?

**Comment by OlivierCazade** [comment]
@msherif1234 config/rbac is general and used in every kind of deployment. The monitoring part is proper to Openshift this is why I added the rules there to avoid deploying unnecessary rule.

**Comment by jotak** [comment]
shouldn't it be in the `config/openshift-olm` directory? I'm a bit confused.. I think `openshift-olm` is the one used for downstream builds.. Maybe add it in both places ?

**Pull request merged**
