### PR TITLE
NETOBSERV-773 Copy certificates across namespaces

### PR DESCRIPTION
**Pull request by jotak**
- Any certificate (secret/cm) can now be referenced from any namespace, which makes the operator watch the original and copy it to a target namespace. It allows not only to deploy Loki (or Kafka) in any namespace, but also fixes the issue of ebpf pods not having access to kafka CA/key without manual intervention

And quite a big refactoring:
- New "watchers" and "volumes" packages
- Creation of volumes is now using a builder-style approach allowing to incrementally add volumes and get at the same time their path. It avoid having discrepancies between mounted volumes and their related path reference.
- Watching certificates (or any CM/secret) now uses digest hash of content instead of metadata, to avoid triggering pods restart when a cm/secret was changed despite its content remaining the same
- Some things are moved around to make internal APIs easier to use, less parameters in functions, etc.
- New extensive integration tests on certificates management

### CODE REVIEW

**Review by OlivierCazade — APPROVED** [review]
LGTM

**Review by memodi — CHANGES_REQUESTED** [review]
@jotak - I think I am hitting a bug w/ KAFKA scenario, where I have both of them in different NS and FLP pods are getting 403 error:
```
time=2023-05-25T20:34:13Z level=info component=client error=server returned HTTP status 403 Forbidden (403):  fields.level=error fields.msg=final error sending batch host=lokistack-gateway-http.netobserv-loki.svc.cluster.local:8080 module=export/loki status=403
```

here's loki and kafka config:
```
{
  "authToken": "FORWARD",
  "batchSize": 10485760,
  "batchWait": "1s",
  "maxBackoff": "5s",
  "maxRetries": 2,
  "minBackoff": "1s",
  "staticLabels": {
    "app": "netobserv-flowcollector"
  },
  "statusTls": {
    "caCert": {
      "namespace": ""
    },
    "enable": false,
    "insecureSkipVerify": false,
    "userCert": {
      "namespace": ""
    }
  },
  "tenantID": "netobserv",
  "timeout": "10s",
  "tls": {
    "caCert": {
      "certFile": "service-ca.crt",
      "name": "lokistack-gateway-ca-bundle",
      "namespace": "netobserv-loki",
      "type": "configmap"
    },
    "enable": true,
    "insecureSkipVerify": false,
    "userCert": {
      "namespace": "netobserv-loki"
    }
  },
  "url": "https://lokistack-gateway-http.netobserv-loki.svc.cluster.local:8080/api/logs/v1/network/"
}

{
  "address": "kafka-cluster-kafka-bootstrap.netobserv-kafka",
  "tls": {
    "caCert": {
      "certFile": "ca.crt",
      "name": "kafka-cluster-cluster-ca-cert",
      "namespace": "netobserv-kafka",
      "type": "secret"
    },
    "enable": true,
    "insecureSkipVerify": false,
    "userCert": {
      "certFile": "user.crt",
      "certKey": "user.key",
      "name": "flp-kafka",
      "namespace": "netobserv-kafka",
      "type": "secret"
    }
  },
  "topic": "network-flows"
}
```


perhaps we're using incorrect certs to connect with Loki in this scenario?

**Comment by jotak** [comment]
@memodi I don't remember if I tested loki AND kafka in different namespaces, so let me get a try. Just in case: you did deploy the clusterrolebinding for reading loki logs just as usual? ie. FLP's service account has permissions to write logs?

**Comment by memodi** [comment]
> @memodi I don't remember if I tested loki AND kafka in different namespaces, so let me get a try. Just in case: you did deploy the clusterrolebinding for reading loki logs just as usual? ie. FLP's service account has permissions to write logs?

ah, that might be it. I didn't update the CRD to work with KAFKA mode, my bad.

**Comment by jotak** [comment]
thanks @memodi !
/approve

**Comment by jotak** [comment]
(merging .. was previously reviewed before last rebase)

**Pull request merged**
