### PR TITLE
Update console plugin arguments

### PR DESCRIPTION
**Pull request by jotak**
dependent on this PR: https://github.com/netobserv/network-observability-console-plugin/pull/8

also added a patch command to the readme for easier setup

### CODE REVIEW

**Comment by jotak** [comment]
/hold
needs https://github.com/netobserv/network-observability-console-plugin/pull/8 to be merged

**Review by OlivierCazade — APPROVED** [review]
LGTM, however with the previous console-plugin, the console was caching requests and this is why we did not need HPA, now that we have a backend handling request, we also may need to setup HPA with the operator.

**Comment by jotak** [comment]
@OlivierCazade good point, I'll create a story

**Pull request merged**
