### PR TITLE
Hack script to "refresh" OVS

### PR DESCRIPTION
**Pull request by jotak**
ie. reset its configuration so that it sends again the ipfix templates
goal is to speed up ipfix template sync

### CODE REVIEW

**Comment by memodi** [comment]
I am curious, in what scenarios we might use this hack?

**Comment by jotak** [comment]
@memodi it's when for instance you change a config that triggers FLP reconciling/restarting, then you may need to wait for up to 10 minutes before seeing flows again (because ovs needs to sync with flp for sending ipfix definitions). This hack should force this sync hence avoiding the potential 10-minutes delay.

**Review by mariomac — APPROVED** [review]
Just by curiosity. Has this unsynced scenario happened very frequently to you? If that happened to me, I unnoticed it (maybe it just happened in one node and I didn't realize it because flows from other nodes were still going on)

**Comment by jotak** [comment]
yes it does happen frequently to me, I'm surprised if it doesn't to you!
for instance, when changing FLP log level, or switching kafka on and off, or whatever that changes FLP without changing OVS...
we can also track the error metric, it tells when there's missing template definitions

**Comment by jotak** [comment]
Yes, 10min is a maximum, for me as well it can be less, but it's common to have to wait more than 2-3 minutes. Unlike the eBPF agent that starts sending data immediately

**Pull request merged**
